version: "3.1"

services:
  transmission:
    image: linuxserver/transmission:4.0.3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - USER=user
      - PASS=password
      # - TRANSMISSION_WEB_HOME=
      # - WHITELIST=
      # - PEERPORT=
      # - HOST_WHITELIST=
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
